version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - wget https://www.sbl-site.org/Fonts/SBL_Hbrw.ttf -O /usr/share/fonts/SBL_Hbrw.ttf
      - fc-cache -f

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf
  - htmlzip