version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - mkdir -p $READTHEDOCS_OUTPUT/pdf
      - wget https://www.sbl-site.org/Fonts/SBL_Hbrw.ttf -O $READTHEDOCS_OUTPUT/pdf/SBL_Hbrw.ttf
    
python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf
  - htmlzip